spring:
  application:
    name: concurrency
  #profile 설정
  profiles:
    active: ${server.profile:local}
  h2:
    console:
      enabled: true
      settings:
        web-allow-others: true
      path: /h2-console
  jpa:
    hibernate:
      ddl-auto: create-drop  #절대 수정 금지
      format_sql: true
    show-sql: true
    defer-datasource-initialization: true
    properties:
      hibernate:
        default_batch_size: 100
  datasource:
    hikari:
      driver-class-name: org.h2.Driver
      jdbc-url: jdbc:h2:mem:concurrency;mode=mysql
      username: sa
      password: